In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [3]:
# 1 How many negative numbers are there?
# 2 How many positive numbers are there?
# 3 How many even positive numbers are there?
# 4 If you were to add 3 to each data point, how many positive numbers would there be?
# 5 If you squared each number, what would the new mean and standard deviation be?
# 6 A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.
# 7 Calculate the z-score for each data point.
# 8 Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

# Awesome Bonus For much more practice with numpy, Go to https://github.com/rougier/numpy-100 and clone the repo down to your laptop. To clone a repository: - Copy the SSH address of the repository - cd ~/codeup-data-science - Then type git clone git@github.com:rougier/numpy-100.git - Now do cd numpy-100 on your terminal. - Type git remote remove origin, so you won't accidentally try to push your work to Rougier's repo.

# Congratulations! You have cloned Rougier's 100 numpy exercises to your computer. Now you need to make a new, blank, repository on GitHub.

# Go to https://github.com/new to make a new repo. Name it numpy-100. DO NOT check any check boxes. We need a blank, empty repo. Finally, follow the directions to "push an existing repository from the command line" so that you can push up your changes to your own account.

# Now do work, add it, commit it, and push it!

In [4]:
#1
(a<0).sum()

4

In [5]:
#2
(a>0).sum()

5

In [6]:
#3
odd = a[a%2 == 1].size
odd

4

In [7]:
#3
even = a[a%2 == 0].size
even

8

In [8]:
#3
is_positive = a > 0

In [9]:
#3
is_even = a % 2 == 0

In [10]:
#3 
a[(a > 0) & (a % 2 == 0)].size

3

In [11]:
# 4 If you were to add 3 to each data point, how many positive numbers would there be?

plus_three = a + 3
(plus_three > -2).sum()

10

In [12]:
# 5 If you squared each number, what would the new mean and standard deviation be?

(a**2).mean()

74.0

In [13]:
(a**2).std()

144.0243035046516

In [14]:
# 6 A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.

average = a.mean()
average

3.0

In [15]:
(average - a)

array([ -1.,  -7.,  -9., -20.,   5.,   4.,   3.,   3.,   3.,   9.,   0.,
        10.])

In [16]:
(a - a.mean()).mean()

0.0

In [17]:
# 7 Calculate the z-score for each data point.

In [18]:
numerator = (a - a.mean())
numerator

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [19]:
a.mean()

3.0

In [20]:
denominator = a.std()
denominator

8.06225774829855

In [21]:
numerator / denominator

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [22]:
import scipy.stats as stats


In [23]:
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])