In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [3]:
# 1 How many negative numbers are there?
# 2 How many positive numbers are there?
# 3 How many even positive numbers are there?
# 4 If you were to add 3 to each data point, how many positive numbers would there be?
# 5 If you squared each number, what would the new mean and standard deviation be?
# 6 A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.
# 7 Calculate the z-score for each data point.
# 8 Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

# Awesome Bonus For much more practice with numpy, Go to https://github.com/rougier/numpy-100 and clone the repo down to your laptop. To clone a repository: - Copy the SSH address of the repository - cd ~/codeup-data-science - Then type git clone git@github.com:rougier/numpy-100.git - Now do cd numpy-100 on your terminal. - Type git remote remove origin, so you won't accidentally try to push your work to Rougier's repo.

# Congratulations! You have cloned Rougier's 100 numpy exercises to your computer. Now you need to make a new, blank, repository on GitHub.

# Go to https://github.com/new to make a new repo. Name it numpy-100. DO NOT check any check boxes. We need a blank, empty repo. Finally, follow the directions to "push an existing repository from the command line" so that you can push up your changes to your own account.

# Now do work, add it, commit it, and push it!

In [4]:
a[a<0]

array([-2, -1, -6, -7])

In [5]:
#1
(a<0).sum()

4

In [6]:
#2
(a>0).sum()

5

In [7]:
#3
odd = a[a%2 == 1].size
odd

4

In [8]:
#3
even = a[a%2 == 0].size
even

8

In [9]:
#3
is_positive = a > 0

In [10]:
#3
is_even = a % 2 == 0

In [11]:
#3 
a[(a > 0) & (a % 2 == 0)].size

3

In [12]:
# 4 If you were to add 3 to each data point, how many positive numbers would there be?

add_three = a + 3
(add_three > 0).sum()

10

In [13]:
# 5 If you squared each number, what would the new mean and standard deviation be?

(a**2).mean()

74.0

In [14]:
(a**2).std()

144.0243035046516

In [15]:
# 6 A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.

average = a.mean()
average

3.0

In [16]:
(average - a)

array([ -1.,  -7.,  -9., -20.,   5.,   4.,   3.,   3.,   3.,   9.,   0.,
        10.])

In [17]:
(a - a.mean()).mean()

0.0

In [18]:
centered = a - a.mean()
centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [19]:
centered.mean()

0.0

In [20]:
# 7 Calculate the z-score for each data point.

In [21]:
zscores = (a - a.mean()) / a.std()
zscores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [22]:
numerator = (a - a.mean())
numerator

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [23]:
a.mean()

3.0

In [24]:
denominator = a.std()
denominator

8.06225774829855

In [25]:
numerator / denominator

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [26]:
import scipy.stats as stats


In [27]:
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [28]:
import numpy as np
# Life w/o numpy to life with numpy

In [29]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [30]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.


In [31]:
#1 sum_of_a
sum_of_a = np.sum(a)
sum_of_a

55

In [32]:
#2 min_of_a
min_of_a = np.amin(a)
min_of_a

1

In [33]:
#3 max_of_a
max_of_a = np.amax(a)
max_of_a

10

In [34]:
#4 mean_of_a
mean_of_a = np.mean(a)
mean_of_a

5.5

In [35]:
#5 product_of_a
product_of_a = np.product(a)
product_of_a

3628800

In [ ]:
product_of_a = 1
for n in a:
    product_of_a *= n
    
product_of_a

In [36]:
#6 square_of_a
square_of_a = np.square(a)
square_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
squares_of_a = [n ** 2 for n in a]
squares_of_a

In [38]:
#7 odds_in_a
odds_in_a = [n for n in a if n % 2 !=0]
odds_in_a

[1, 3, 5, 7, 9]

In [39]:
#8
evens_in_a = [n for n in a if n % 2 ==0]
evens_in_a

[2, 4, 6, 8, 10]

In [41]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

# Exercise 9 - print out the shape of the array b.

# Exercise 10 - transpose the array b.

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [42]:
flattened_list = []
for numbers in b:
    for n in numbers:
        flattened_list.append(n)
flattened_list

[3, 4, 5, 6, 7, 8]

In [43]:
#9
b.shape

AttributeError: 'list' object has no attribute 'shape'